# This file is generated by the gen_tf.py script.
# Do not edit this file directly.

module "about" {
  source = "./zone_deployment"

  content_type   = "text/html"
  domain_aliases = []
  file           = "about.html"
  file_directory = "../public/"
  fqdn           = "about.${var.domainName}"
  source_hash    = filemd5("../public/about.html")
  zone_id        = aws_route53_zone.main.zone_id
}

module "claire_and_the_bens" {
  source = "./zone_deployment"

  content_type   = "image/jpeg"
  domain_aliases = []
  file           = "claire-and-the-bens.jpg"
  file_directory = "../public/"
  fqdn           = "claire-and-the-bens.${var.domainName}"
  source_hash    = filemd5("../public/claire-and-the-bens.jpg")
  zone_id        = aws_route53_zone.main.zone_id
}

module "favicon" {
  source = "./zone_deployment"

  content_type   = "image/x-icon"
  domain_aliases = []
  file           = "favicon.ico"
  file_directory = "../public/"
  fqdn           = "favicon.${var.domainName}"
  source_hash    = filemd5("../public/favicon.ico")
  zone_id        = aws_route53_zone.main.zone_id
}

module "index" {
  source = "./zone_deployment"

  content_type   = "text/html"
  domain_aliases = ["www.${var.domainName}"]
  file           = "index.html"
  file_directory = "../public/"
  fqdn           = "${var.domainName}"
  source_hash    = filemd5("../public/index.html")
  zone_id        = aws_route53_zone.main.zone_id
}
