# This file is generated by the gen_tf.py script.
# Do not edit this file directly.

output "about_cloudfront_distribution_id" {
  value = module.about.cloudfront_distribution_id
}

output "about_hosted_zone_id" {
  value = module.about.hosted_zone_id
}

output "about_bucket_id" {
  value = module.about.bucket_id
}

output "about_bucket_regional_domain_name" {
  value = module.about.bucket_regional_domain_name
}

output "about_cert_arn" {
  value = module.about.cert_arn
}

output "about_cert_validation_record" {
  value = module.about.cert_validation_record
}


output "advent_of_rfcs_cloudfront_distribution_id" {
  value = module.advent_of_rfcs.cloudfront_distribution_id
}

output "advent_of_rfcs_hosted_zone_id" {
  value = module.advent_of_rfcs.hosted_zone_id
}

output "advent_of_rfcs_bucket_id" {
  value = module.advent_of_rfcs.bucket_id
}

output "advent_of_rfcs_bucket_regional_domain_name" {
  value = module.advent_of_rfcs.bucket_regional_domain_name
}

output "advent_of_rfcs_cert_arn" {
  value = module.advent_of_rfcs.cert_arn
}

output "advent_of_rfcs_cert_validation_record" {
  value = module.advent_of_rfcs.cert_validation_record
}


output "favicon_cloudfront_distribution_id" {
  value = module.favicon.cloudfront_distribution_id
}

output "favicon_hosted_zone_id" {
  value = module.favicon.hosted_zone_id
}

output "favicon_bucket_id" {
  value = module.favicon.bucket_id
}

output "favicon_bucket_regional_domain_name" {
  value = module.favicon.bucket_regional_domain_name
}

output "favicon_cert_arn" {
  value = module.favicon.cert_arn
}

output "favicon_cert_validation_record" {
  value = module.favicon.cert_validation_record
}


output "index_cloudfront_distribution_id" {
  value = module.index.cloudfront_distribution_id
}

output "index_hosted_zone_id" {
  value = module.index.hosted_zone_id
}

output "index_bucket_id" {
  value = module.index.bucket_id
}

output "index_bucket_regional_domain_name" {
  value = module.index.bucket_regional_domain_name
}

output "index_cert_arn" {
  value = module.index.cert_arn
}

output "index_cert_validation_record" {
  value = module.index.cert_validation_record
}


output "_60_40_posts_cloudfront_distribution_id" {
  value = module._60_40_posts.cloudfront_distribution_id
}

output "_60_40_posts_hosted_zone_id" {
  value = module._60_40_posts.hosted_zone_id
}

output "_60_40_posts_bucket_id" {
  value = module._60_40_posts.bucket_id
}

output "_60_40_posts_bucket_regional_domain_name" {
  value = module._60_40_posts.bucket_regional_domain_name
}

output "_60_40_posts_cert_arn" {
  value = module._60_40_posts.cert_arn
}

output "_60_40_posts_cert_validation_record" {
  value = module._60_40_posts.cert_validation_record
}


output "posts_cloudfront_distribution_id" {
  value = module.posts.cloudfront_distribution_id
}

output "posts_hosted_zone_id" {
  value = module.posts.hosted_zone_id
}

output "posts_bucket_id" {
  value = module.posts.bucket_id
}

output "posts_bucket_regional_domain_name" {
  value = module.posts.bucket_regional_domain_name
}

output "posts_cert_arn" {
  value = module.posts.cert_arn
}

output "posts_cert_validation_record" {
  value = module.posts.cert_validation_record
}


output "joy_of_shipping_posts_cloudfront_distribution_id" {
  value = module.joy_of_shipping_posts.cloudfront_distribution_id
}

output "joy_of_shipping_posts_hosted_zone_id" {
  value = module.joy_of_shipping_posts.hosted_zone_id
}

output "joy_of_shipping_posts_bucket_id" {
  value = module.joy_of_shipping_posts.bucket_id
}

output "joy_of_shipping_posts_bucket_regional_domain_name" {
  value = module.joy_of_shipping_posts.bucket_regional_domain_name
}

output "joy_of_shipping_posts_cert_arn" {
  value = module.joy_of_shipping_posts.cert_arn
}

output "joy_of_shipping_posts_cert_validation_record" {
  value = module.joy_of_shipping_posts.cert_validation_record
}

