# This file is generated by the gen_tf.py script.
# Do not edit this file directly.

output "about_cloudfront_distribution_id" {
  value = module.about.cloudfront_distribution_id
}

output "about_hosted_zone_id" {
  value = module.about.hosted_zone_id
}

output "about_bucket_id" {
  value = module.about.bucket_id
}

output "about_bucket_regional_domain_name" {
  value = module.about.bucket_regional_domain_name
}

output "about_cert_arn" {
  value = module.about.cert_arn
}

output "about_cert_validation_record" {
  value = module.about.cert_validation_record
}


output "claire_and_the_bens_cloudfront_distribution_id" {
  value = module.claire_and_the_bens.cloudfront_distribution_id
}

output "claire_and_the_bens_hosted_zone_id" {
  value = module.claire_and_the_bens.hosted_zone_id
}

output "claire_and_the_bens_bucket_id" {
  value = module.claire_and_the_bens.bucket_id
}

output "claire_and_the_bens_bucket_regional_domain_name" {
  value = module.claire_and_the_bens.bucket_regional_domain_name
}

output "claire_and_the_bens_cert_arn" {
  value = module.claire_and_the_bens.cert_arn
}

output "claire_and_the_bens_cert_validation_record" {
  value = module.claire_and_the_bens.cert_validation_record
}


output "favicon_cloudfront_distribution_id" {
  value = module.favicon.cloudfront_distribution_id
}

output "favicon_hosted_zone_id" {
  value = module.favicon.hosted_zone_id
}

output "favicon_bucket_id" {
  value = module.favicon.bucket_id
}

output "favicon_bucket_regional_domain_name" {
  value = module.favicon.bucket_regional_domain_name
}

output "favicon_cert_arn" {
  value = module.favicon.cert_arn
}

output "favicon_cert_validation_record" {
  value = module.favicon.cert_validation_record
}


output "index_cloudfront_distribution_id" {
  value = module.index.cloudfront_distribution_id
}

output "index_hosted_zone_id" {
  value = module.index.hosted_zone_id
}

output "index_bucket_id" {
  value = module.index.bucket_id
}

output "index_bucket_regional_domain_name" {
  value = module.index.bucket_regional_domain_name
}

output "index_cert_arn" {
  value = module.index.cert_arn
}

output "index_cert_validation_record" {
  value = module.index.cert_validation_record
}

